// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWgIO9HeMqmvG5xUFoia2coIxp0Poo17M',
    appId: '1:825061374343:web:5b404d2592ca8b4aaa3b22',
    messagingSenderId: '825061374343',
    projectId: 'chat-app-d68d8',
    authDomain: 'chat-app-d68d8.firebaseapp.com',
    storageBucket: 'chat-app-d68d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK14kWV9nDBQDRNEPRa_MnQBIbLJzt2zw',
    appId: '1:825061374343:android:1f336e8c80e92500aa3b22',
    messagingSenderId: '825061374343',
    projectId: 'chat-app-d68d8',
    storageBucket: 'chat-app-d68d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd5OL-nVZx7dC6DUuT7bJ34_ShuJAiDjc',
    appId: '1:825061374343:ios:525f9e7e1f0085c6aa3b22',
    messagingSenderId: '825061374343',
    projectId: 'chat-app-d68d8',
    storageBucket: 'chat-app-d68d8.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd5OL-nVZx7dC6DUuT7bJ34_ShuJAiDjc',
    appId: '1:825061374343:ios:525f9e7e1f0085c6aa3b22',
    messagingSenderId: '825061374343',
    projectId: 'chat-app-d68d8',
    storageBucket: 'chat-app-d68d8.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

}